config/routes.rb
Closefeed::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :miniposts, :only => [:new, :show, :create, :destroy]
  resources :responses, :only => [:create, :destroy]
  resources :search, :only => [:new]
  resources :topics
  resources :followerships, only: [:index, :create, :destroy]
  resources :interests, only: [:show, :index, :create, :destroy]
  resources :votes, only: [:create]
  resources :affiliations, only: [:show, :index]
  resources :password_resets
  resources :relationships, only: [:create, :destroy]

  match '/search', :to => 'pages#home'
  match '/searchresult', :to => 'search#new'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/about', :to => 'pages#about'
  match '/termsofuse', :to => 'pages#termsofuse'
  match '/privacystatement', :to => 'pages#privacystatement'
  match '/followus', :to => 'pages#followus'
  match '/faq', :to => 'pages#faq'
  match '/contact', to: 'pages#contact'

  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :affiliation_id

  belongs_to :affiliation
  
  has_many :miniposts, :dependent => :destroy
  has_many :responses, :dependent => :destroy
  has_many :followerships, foreign_key: "user_id", dependent: :destroy
  has_many :topics, through: :followerships
  has_many :interests, foreign_key: "user_id", dependent: :destroy
  has_many :followedposts, through: :interests
  has_many :votes, foreign_key: "user_id", dependent: :destroy
  has_many :votedresponses, through: :votes
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed

  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 },
                       if: :validate_password?
  validates :affiliation_id, :presence => true

  before_create { generate_token(:auth_token) }
  before_save :encrypt_password

  def validate_password?
    password.present? || password_confirmation.present?
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  # Return true if the user's password matches the submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(auth_token, cookie_salt)
    user = find_by_auth_token(auth_token)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def feed
    Minipost.where("affiliation_id = ?", affiliation_id)
  end

  def following?(topic)
    followerships.find_by_topic_id(topic.id)
  end

  def follow!(topic)
    followerships.create!(topic_id: topic.id)
  end

  def unfollow!(topic)
    followerships.find_by_topic_id(topic.id).destroy
  end

  def followingpost?(minipost)
    interests.find_by_followedpost_id(minipost.id)
  end

  def followpost!(minipost)
    interests.create!(followedpost_id: minipost.id)
  end

  def unfollowpost!(minipost)
    interests.find_by_followedpost_id(minipost.id).destroy
  end

  def votedresponse?(response)
    votes.find_by_votedresponse_id(response.id)
  end

  def voteresponse!(response)
    votes.create!(votedresponse_id: response.id)
  end

  def followinguser?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def followuser!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollowuser!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end

  private
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      rnd = (('A'..'Z').to_a + (0..9).to_a).shuffle[0..15].join
      secure_hash("#{Time.now.utc}--#{password}--#{rnd}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, only: [:show, :index, :edit, :update, :following, :followers]
  before_filter :correct_user, only: [:edit, :update]

  def new
    @user = User.new
    @title = "Sign up"
  end

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @miniposts = @user.miniposts.paginate(:page => params[:page])
    @miniposts.each do |minipost|
      @responses = minipost.responses
    end
    @title = @user.name
    @response = Response.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to cliffchat!"
      redirect_to root_path
    else
      @title = "Sign up"
      render :new
    end
  end

  def edit
    @title = "Edit User"
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit User"
      render 'edit'
    end
  end

  def following
    @users = current_user.followed_users.paginate(page: params[:page])
    @title = "Following"
    render 'show_follow'
  end

  def followers
    @users = current_user.followers.paginate(page: params[:page])
    @title = "Followers"
    render 'show_follow'
  end

  private
  
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.name),
                       :class => 'gravatar',
                       :gravatar => options)
  end
end

app/views/users/_fields.html.erb
<script type="text/javascript">
  $(function() {
    $('#text').autocomplete({
      minLength: 2,
      source: '<%= affiliations_path(:json) %>',
      focus: function(event, ui) {
        $('#text').val(ui.item.name);
        return false;
      },
      select: function(event, ui) {
        $('#text').val(ui.item.name);
        $('#user_affiliation_id').val(ui.item.id);
        return false;
      }
    })
    .data("autocomplete")._renderItem = function(ul, item) {
      return $("<li></li>")
      .data("item.autocomplete", item)
      .append("<a>" + item.name + "</a>")
      .appendTo(ul);
    };
  });
</script>

<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
  <small>We promise we will never spam or share your email</small>
</div>
<div class="field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
</div>
<div class="field">
  <%= f.label :affiliation_id, "University affiliation" %>
  <input id="text" type="text" />
  <input id="user_affiliation_id" name="user[affiliation_id]" type="hidden" />
  <small>Select universities only for time being</small>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.followinguser?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>

app/views/users/_quick_new.html.erb
<div style="background: #663333; border-radius: 17px; padding: 20px; width: 360px">
	<span style="color: grey">New? Sign up for cliffchat:</span>
	<%= form_for(:user) do |f| %>
	<div class="field">
		<%= f.text_field :name,:value => "full name",:class => "hintTextbox",:size => "33"%>
	</div>
	<div class="field">
		<%= f.text_field :email,:value => "email address",:class => "hintTextbox",:size => "33"%>
	</div>
	<div class="field">
		<%= f.password_field :password,:value => "password",:class => "hintTextbox",:size => "33"%>
	</div>
	<!-- TODO figure out how to wire properly & add affiliation drop down-->	
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
	<% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li style='padding-bottom: 4px'>
  <%= gravatar_for user, :size => 30 %>  
  <%= link_to user.name, user %><br/>
</li>

app/views/users/edit.html.erb
<h4>Edit User</h4>
<hr>
<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= link_to "Update", "#", class: "btn btn-primary", onclick: "$('form').submit()" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<h4>All users</h4>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<div class="page-header">
  <h4>Sign up</h4>
</div>
<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Sign Up", class: "btn btn-primary" %>
  </div>
<% end %>
<script type="text/javascript">
  mixpanel.track("Sign up");
</script>

app/views/users/show.html.erb
<table class="profile" summary="Profile Information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <div>
        <%= render 'follow_form' if signed_in? %>
      </div>
      <% unless @user.miniposts.empty? %>
        <div id="postcontainer">
          <ul class="miniposts" id="miniposts" summary="User posts">
            <%= render :partial => 'shared/feed_item', :collection => @miniposts %>
          </ul>
          <%= will_paginate @miniposts %>
        </div>
      <% end %>
    </td>
    <!--
    <td class="sidebar round">
      <strong>Name</strong> <%= link_to @user.name, @user %>
      <strong>Posts</strong> <%= @user.miniposts.count %>
      <strong>Responses</strong> <%= @user.responses.count %>
    </td>
    -->
  </tr>
</table>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="unstyled">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>