config/routes.rb
Closefeed::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  resources :miniposts, :only => [:new, :show, :create, :destroy]
  resources :responses, :only => [:create, :destroy]
  resources :search, :only => [:new]
  resources :topics
  resources :followerships, only: [:index, :create, :destroy]
  resources :interests, only: [:show, :index, :create, :destroy]
  resources :votes, only: [:create]
  resources :affiliations, only: [:show, :index]
  resources :password_resets
  resources :relationships, only: [:create, :destroy]

  match '/search', :to => 'pages#home'
  match '/searchresult', :to => 'search#new'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/about', :to => 'pages#about'
  match '/termsofuse', :to => 'pages#termsofuse'
  match '/privacystatement', :to => 'pages#privacystatement'
  match '/followus', :to => 'pages#followus'
  match '/faq', :to => 'pages#faq'
  match '/contact', to: 'pages#contact'

  root :to => 'pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h4><%= pluralize(object.errors.count, "error") %>
      prohibited this
      <%= object.class.to_s.underscore.humanize.downcase %>
      from being saved:
    </h4>
    <p>Please fix the following fields:</p>
    <ul class="unstyled">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<ul class="miniposts" id="miniposts" summary="User posts">
  <div id="postcontainer">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
    <%= will_paginate @feed_items %>
    <%= pageless @feed_items.total_pages, '?escape=false' %>
  </div>
</ul>

app/views/shared/_feed_item.html.erb
<%= div_for(feed_item) do %>
  <li class="minipost">
    <div class="row-fluid" id="feeditemlist">
      <div class="span1" id="left">
          <%= link_to gravatar_for(feed_item.user), feed_item.user %>
      </div>
      <div class="span10" id="right">
        <span class="user">
          <%= link_to feed_item.user.name, feed_item.user %>
        </span>
        <span id="minipost_content"><%= wrap(feed_item.content) %></span>
        <span class="timestamp">
          Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
        </span>
        <% if current_user?(feed_item.user) %>
          <span class="delete">
            <%= link_to "<i class='icon-remove-sign'></i> Delete".html_safe, feed_item,
              :method => :delete,
              :confirm => "Are you sure?",
              :title => feed_item.content,
              :remote => true
            %>
          </span>
        <% end %>
        <span class="">
          <%= link_to ("<i class='icon-comment'></i> " + (feed_item.responses.empty? ? "Respond" : pluralize(feed_item.responses.count, "response"))).html_safe, feed_item, locals: {minipost: feed_item}, id: "response_link" %>
        </span>
      </div>
    </div>
  </li>
<% end %>

app/views/shared/_minipost_form.html.erb
<%= form_for(@minipost, remote: true) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content, class: 'row-fluid' %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_response_form.html.erb
<%= form_for(@response, remote: true) do |f| %>
    <%= render 'shared/error_messages', :object => f.object %>
    <%= f.hidden_field :minipost_id, {:value => minipost.id} %>
    <div class="field">
      <%= f.text_area :content, class: 'row-fluid' %>
    </div>
    <div class="actions">
      <%= f.submit "Respond", class: "btn btn-primary btn-small" %>
    </div>
<% end %>

app/views/shared/_stats.html.erb
<div class="stats">
  Following: <br/>
  <div class="posts_count">
    <%= link_to pluralize(current_user.followedposts.count, "post"), interests_path %><br/>
  </div>
  <div class="topics_count">
    <%= link_to pluralize(current_user.topics.count, "topic"), followerships_path %><br/>
  </div>
  <div class="following_count">
    <%= link_to pluralize(current_user.followed_users.count, "user"), following_user_path(current_user) %><br/>
  </div>

  Followed: <br/>
  <div class="followers_count">
    <%= link_to pluralize(current_user.followers.count, "follower"), followers_user_path(current_user) %><br/>
  </div>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <div>
  <a href="<%= user_path(current_user) %>">
    <span>
    <%= gravatar_for current_user, :size => 30 %>
  </span>
    <span class="user_name">
      <%= current_user.name %>
    </span>
  </a>
  </div>
    <span class="miniposts">
      <%= pluralize(current_user.miniposts.count, "post") %>
    </span>
      <%= render 'shared/stats' %>
</div>

app/views/shared/_user_topics.html.erb
<div class="topics">
  Following: <%= pluralize(current_user.topics.count, "topic") %>
  <ul>
    <% current_user.topics.each do |topic| %>
      <li><%= link_to topic.name, topic %></li>
    <% end %>
  </ul>
</div>